# Generated by Django 3.2.13 on 2022-06-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='Images/None/sample.jpg', upload_to='Images'),
        ),
    ]
